import { PopoverSelectorOption } from '@/components/popover-selector';

export const languageOptions: PopoverSelectorOption[] = [
    { value: 'auto-detect', label: 'Auto detect', flag: '🤖' },
    { value: 'af', label: 'Afrikaans', flag: '🇿🇦' },
    { value: 'ar', label: 'Arabic', flag: '🇸🇦' },
    { value: 'hy', label: 'Armenian', flag: '🇦🇲' },
    { value: 'az', label: 'Azerbaijani', flag: '🇦🇿' },
    { value: 'be', label: 'Belarusian', flag: '🇧🇾' },
    { value: 'bs', label: 'Bosnian', flag: '🇧🇦' },
    { value: 'bg', label: 'Bulgarian', flag: '🇧🇬' },
    { value: 'ca', label: 'Catalan', flag: '🇪🇸' },
    { value: 'zh', label: 'Chinese', flag: '🇨🇳' },
    { value: 'hr', label: 'Croatian', flag: '🇭🇷' },
    { value: 'cs', label: 'Czech', flag: '🇨🇿' },
    { value: 'da', label: 'Danish', flag: '🇩🇰' },
    { value: 'nl', label: 'Dutch', flag: '🇳🇱' },
    { value: 'en', label: 'English', flag: '🇬🇧' },
    { value: 'et', label: 'Estonian', flag: '🇪🇪' },
    { value: 'fi', label: 'Finnish', flag: '🇫🇮' },
    { value: 'fr', label: 'French', flag: '🇫🇷' },
    { value: 'gl', label: 'Galician', flag: '🇪🇸' },
    { value: 'de', label: 'German', flag: '🇩🇪' },
    { value: 'el', label: 'Greek', flag: '🇬🇷' },
    { value: 'he', label: 'Hebrew', flag: '🇮🇱' },
    { value: 'hi', label: 'Hindi', flag: '🇮🇳' },
    { value: 'hu', label: 'Hungarian', flag: '🇭🇺' },
    { value: 'is', label: 'Icelandic', flag: '🇮🇸' },
    { value: 'id', label: 'Indonesian', flag: '🇮🇩' },
    { value: 'it', label: 'Italian', flag: '🇮🇹' },
    { value: 'ja', label: 'Japanese', flag: '🇯🇵' },
    { value: 'kn', label: 'Kannada', flag: '🇮🇳' },
    { value: 'kk', label: 'Kazakh', flag: '🇰🇿' },
    { value: 'ko', label: 'Korean', flag: '🇰🇷' },
    { value: 'lv', label: 'Latvian', flag: '🇱🇻' },
    { value: 'lt', label: 'Lithuanian', flag: '🇱🇹' },
    { value: 'mk', label: 'Macedonian', flag: '🇲🇰' },
    { value: 'ms', label: 'Malay', flag: '🇲🇾' },
    { value: 'mr', label: 'Marathi', flag: '🇮🇳' },
    { value: 'mi', label: 'Maori', flag: '🇳🇿' },
    { value: 'ne', label: 'Nepali', flag: '🇳🇵' },
    { value: 'no', label: 'Norwegian', flag: '🇳🇴' },
    { value: 'fa', label: 'Persian', flag: '🇮🇷' },
    { value: 'pl', label: 'Polish', flag: '🇵🇱' },
    { value: 'pt', label: 'Portuguese', flag: '🇵🇹' },
    { value: 'ro', label: 'Romanian', flag: '🇷🇴' },
    { value: 'ru', label: 'Russian', flag: '🇷🇺' },
    { value: 'sr', label: 'Serbian', flag: '🇷🇸' },
    { value: 'sk', label: 'Slovak', flag: '🇸🇰' },
    { value: 'sl', label: 'Slovenian', flag: '🇸🇮' },
    { value: 'es', label: 'Spanish', flag: '🇪🇸' },
    { value: 'sw', label: 'Swahili', flag: '🇰🇪' },
    { value: 'sv', label: 'Swedish', flag: '🇸🇪' },
    { value: 'tl', label: 'Tagalog', flag: '🇵🇭' },
    { value: 'ta', label: 'Tamil', flag: '🇮🇳' },
    { value: 'th', label: 'Thai', flag: '🇹🇭' },
    { value: 'tr', label: 'Turkish', flag: '🇹🇷' },
    { value: 'uk', label: 'Ukrainian', flag: '🇺🇦' },
    { value: 'ur', label: 'Urdu', flag: '🇵🇰' },
    { value: 'vi', label: 'Vietnamese', flag: '🇻🇳' },
    { value: 'cy', label: 'Welsh', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
];
